/**
 * JSON used to map ownership for EIOS Pulljob
 */
export const ownershipMappingJSON = {
  '0_COVID Countries': ['HQ AEE'],
  AEE_Monkeypox_Expanded: ['HQ AEE'],
  'AFRO Media Monitoring w/o COVID-19': ['AFRO'],
  'AFRO Signals': ['AFRO'],
  'AFRO: EVD/VHF East African monitoring board 2022': ['AFRO'],
  'AFRO_IDSR priority diseases and conditions': ['AFRO'],
  'Bahrain, Jordan and Lebanon Cov': ['HQ AEE'],
  Balkans_COVID_public: ['EURO'],
  Caucasus_COVID_public: ['EURO'],
  CentralAsia_COVID_public: ['EURO'],
  CentralEurope_COVID_public: ['EURO'],
  COVID_AdHoc_EURO_public: ['EURO'],
  'COVID-19 Intel monitoring - GLOBAL': ['HQ AEE'],
  'ELR ADHOC': ['HQ AEE'],
  'ELR-Samuel': ['HQ AEE'],
  'EMRO COVID Vaccination': ['EMRO'],
  'EMRO- Excl nCoV': ['EMRO'],
  'EMRO new Variant': ['EMRO'],
  EUROHIM_WEST_public: ['EURO'],
  MM_EURO_SignalApp_Pilot: ['EURO'],
  'Monkeypox - Global Outbreak': ['HQ AEE'],
  'Monkeypox Global Outbreak': ['HQ AEE'],
  'Monkeypox_Global EBS_Expanded': ['HQ AEE'],
  'NRBC - Sahel': ['HQ FCV'],
  'PAHO - Natural Disasters': ['AMRO'],
  'PAHO - Priority Hazards': ['AMRO'],
  qa: ['EMRO'],
  'qa - euro': ['EURO'],
  'QA- HQ- AFRO - EURO- AMRO': ['EURO', 'AFRO', 'AMRO'],
  'qa4 - AFRO- AMRO- EURO': ['EURO', 'AFRO', 'AMRO'],
  'SARS-CoV-2 variants': ['HQ AEE'],
  'SEAR Signals For Export': ['SEARO'],
  'Shared Ukraine board': ['EURO'],
  'Signals for Follow Up- SEAR': ['SEARO'],
  Ukraine: ['EURO'],
  'WPRO - Disaster': ['WPRO'],
  'WPRO Disease 2 - Not nCoV': ['WPRO'],
};
