/* eslint-disable @typescript-eslint/naming-convention */

import { Types } from 'mongoose';

/** The object for the default event form */
export const EVENT_FORM = {
  _id: new Types.ObjectId('00000000000000000000da7a'),
  name: '__EVENTS__',
  graphQLTypeName: 'Events',
  core: true,
  status: 'active',
  fields: [
    {
      type: 'dropdown',
      name: 'type',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
      choices: [
        { value: 'LOGIN', text: 'LOGIN' },
        { value: 'LOGOUT', text: 'LOGOUT' },
        { value: 'ADD_RECORD', text: 'ADD_RECORD' },
        { value: 'UPDATE_RECORD', text: 'UPDATE_RECORD' },
        { value: 'DELETE_RECORD', text: 'DELETE_RECORD' },
        { value: 'DOWNLOAD_FILE', text: 'DOWNLOAD_FILE' },
        { value: 'NAVIGATE', text: 'NAVIGATE' },
      ],
    },
    {
      type: 'datetime-local',
      name: 'datetime',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'users',
      name: 'user',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
      applications: null,
    },
    {
      type: 'text',
      name: 'record_id',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'form_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'page_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'file_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
  ],
  structure: JSON.stringify({
    logoPosition: 'right',
    pages: [
      {
        name: 'page1',
        elements: [
          {
            type: 'dropdown',
            name: 'type',
            title: 'type',
            valueName: 'type',
            choices: [
              'LOGIN',
              'LOGOUT',
              'ADD_RECORD',
              'UPDATE_RECORD',
              'DELETE_RECORD',
              'DOWNLOAD_FILE',
              'NAVIGATE',
            ],
          },
          {
            type: 'text',
            name: 'datetime',
            title: 'datetime',
            valueName: 'datetime',
            inputType: 'datetime-local',
          },
          {
            type: 'users',
            name: 'user',
            title: 'user',
            valueName: 'user',
          },
          {
            type: 'text',
            name: 'record_id',
            title: 'recordID',
            valueName: 'record_id',
          },
          {
            type: 'text',
            name: 'form_name',
            title: 'formName',
            valueName: 'form_name',
          },
          {
            type: 'text',
            name: 'page_name',
            title: 'pageName',
            valueName: 'page_name',
          },
          {
            type: 'text',
            name: 'file_name',
            title: 'fileName',
            valueName: 'file_name',
          },
        ],
      },
    ],
    showQuestionNumbers: 'off',
  }),
};

/** The object for the default event resource */
export const EVENT_RESOURCE = {
  name: EVENT_FORM.name,
  fields: [
    {
      type: 'dropdown',
      name: 'type',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
      choices: [
        { value: 'LOGIN', text: 'LOGIN' },
        { value: 'LOGOUT', text: 'LOGOUT' },
        { value: 'ADD_RECORD', text: 'ADD_RECORD' },
        { value: 'UPDATE_RECORD', text: 'UPDATE_RECORD' },
        { value: 'DELETE_RECORD', text: 'DELETE_RECORD' },
        { value: 'DOWNLOAD_FILE', text: 'DOWNLOAD_FILE' },
        { value: 'NAVIGATE', text: 'NAVIGATE' },
      ],
    },
    {
      type: 'datetime-local',
      name: 'datetime',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'users',
      name: 'user',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
      applications: null,
    },
    {
      type: 'text',
      name: 'record_id',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'form_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'page_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
    {
      type: 'text',
      name: 'file_name',
      unique: false,
      isRequired: false,
      showOnXlsxTemplate: true,
      readOnly: false,
      isCore: true,
    },
  ],
};
