import axios from 'axios';
import config from 'config';
import { logger } from '@services/logger.service';
import { getErrorMessage, getErrorStack } from '@utils/error';

/** Cloudflare Turnstile token verification endpoint */
const TURNSTILE_VERIFY_URL =
  'https://challenges.cloudflare.com/turnstile/v0/siteverify';

/** Response of the Turnstile siteverify endpoint */
interface TurnstileVerifyResponse {
  success: boolean;
  'error-codes'?: string[];
}

/**
 * Verify a Cloudflare Turnstile captcha token.
 * Fails closed: returns false if the secret is not configured or the
 * verification request fails.
 *
 * @param token Turnstile token generated by the client widget
 * @param remoteIp IP address of the visitor, if available
 * @returns whether the token is valid
 */
export const verifyTurnstileToken = async (
  token: string,
  remoteIp?: string
): Promise<boolean> => {
  const secret = config.get<string>('captcha.turnstile.secret');
  if (!secret) {
    logger.error(
      'Turnstile captcha verification requested but captcha.turnstile.secret is not configured'
    );
    return false;
  }
  try {
    const { data } = await axios.post<TurnstileVerifyResponse>(
      TURNSTILE_VERIFY_URL,
      {
        secret,
        response: token,
        ...(remoteIp && { remoteip: remoteIp }),
      },
      { timeout: 10000 }
    );
    if (!data.success) {
      logger.info(
        `Turnstile captcha verification failed: ${(
          data['error-codes'] || []
        ).join(', ')}`
      );
    }
    return data.success === true;
  } catch (err) {
    logger.error(getErrorMessage(err), { stack: getErrorStack(err) });
    return false;
  }
};

export default verifyTurnstileToken;
