name: DEV CI

on:
  push:
    branches:
      - 'dev'
      - 'release-*'
      - 'hotfix-*'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - 'release-*'
      - 'hotfix-*'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        mongodb-version: [4.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: test
      - name: Install Dependencies
        run: npm ci
      - name: Create .env file
        run: |
          touch .env
          echo '${{ secrets.ENV_TEST }}' >> .env
      - name: Test
        run: npm run test
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage