name: Deploy Docker Image

on:
  schedule:
    - cron: '0 0 * * 0' #At 00:00 on every Sunday.
    
  repository_dispatch:
    types: [DOCKER]

  workflow_dispatch:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
  
  release:
    types: [published]

env:
  IMAGE_NAME: safe_api

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 'Update docker latest image'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: main
          - ref: next
          - ref: next-major
          - ref: beta
          - ref: alpha
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --target production --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Dispatch DOCKER Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CD_ACCESS_TOKEN }}
          event-type: DOCKER
          client-payload: '{""ref": "${{ matrix.ref }}"}'

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
